#!/bin/sh
clear

# Downloads, installs and configures a new Wordpress project using Bedrock.
# https://roots.io/bedrock
#
# Required dependencies:
#
# 1) Composer:
#    https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx
#
# 2) PHP >= 5.6
#
# 3) MySQL

# Colours.
BLUE='\x1B[0;34m';
GREEN='\x1B[0;32m';
RED='\x1B[0;31m';
PINK='\x1B[0;35m';
NC='\x1B[0m';

# Database Information.
DB_HOST="127.0.0.1"

# Move into the php sites directory.
cd ~/Sites/__php/sites

# Intro.
echo "${PINK}================================================================="
echo "Starting a New Wordpress (Bedrock) Project"
echo "=================================================================${NC}"

echo "\n"

# Get the name of the project.
echo "${BLUE}Directory/Project Name: (e.g. new-project-name)${NC}"
read PROJECT_NAME

# Get the title of the project.
echo ""
echo "${BLUE}Project Title:${NC}"
read PROJECT_TITLE

# Get the descrption of the project (so we can replace 'just another wordpress site').
echo ""
echo "${BLUE}Project Description:${NC}"
read PROJECT_DESCRIPTION


# Add a simple yes/no confirmation before we proceed
echo "\n"
echo "Run Install? (y/n)"
read -e run

# If the user said yes, continue.
if [ "$run" == n ] ; then
exit
else

# Create a new Bedrock project using Composer.
echo "\n"
echo "${PINK}-------------------------------------"
echo "Downloading Bedrock"
echo "-------------------------------------${NC}"
echo ""
echo "Please wait, this can take a few seconds."
echo "\n"

composer create-project roots/bedrock $PROJECT_NAME

# Display installation complete message.
echo "\n"
echo "Download Complete!"

# Get some database details.
echo "\n"
echo "${PINK}-------------------------------------"
echo "Database Setup"
echo "-------------------------------------${NC}"
echo ""
echo "Please enter the project database details."
echo "\n"

# Get Database Name
echo "${BLUE}Database Name:${NC}"
read DB_NAME

# Get Database Username
echo ""
echo "${BLUE}Database Username:${NC}"
read DB_USER

# Get Database Password
echo ""
echo "${BLUE}Database Password:${NC}"
read DB_PASS

# Connect to mysql and create a database.
echo ""
echo "- Connecting to mysql and creating database..."

mysql --user=$DB_USER --password=$DB_PASS --execute="create database ${DB_NAME}"

echo "- Database setup complete."

# Move into the project directory we've just created.
cd $PROJECT_NAME

# Copy the example .env.example file to create a new .env file for the project.
echo "\n"
echo "${PINK}-----------------------------------------------"
echo "Configure Environment and Install Wordpress"
echo "-----------------------------------------------${NC}"
echo "\n"
echo "- Creating .env file for local development."

cp .env.example env.txt

sed -i '' "s/DB_NAME=database_name/DB_NAME=${DB_NAME}/" env.txt
sed -i '' "s/DB_USER=database_user/DB_USER=${DB_USER}/" env.txt
sed -i '' "s/DB_PASSWORD=database_password/DB_PASSWORD=${DB_PASS}/" env.txt
sed -i '' "s/# DB_HOST=localhost/DB_HOST=${DB_HOST}/" env.txt
sed -i '' "s/WP_HOME=http:\/\/example.com/WP_HOME=http:\/\/${PROJECT_NAME}.dev/" env.txt

mv env.txt .env

# Move into the /web directory and create a .htaccess file
# and move back out again (do I need to do that?)
cd web
touch .htaccess
cd ../

# Update permissions on the directory so that WP can write to them.
echo "- Updating directory permissions."
sudo chown -R _www web
sudo chmod -R g+w web

# Wordpress Core Install.
echo "- Installing Wordpress."
wp core install --url="${PROJECT_NAME}.dev" --title="${PROJECT_TITLE}" --admin_user="admin" --admin_password="password" --admin_email="kristy.walters@connect-group.com"

# Create a home and blog page, because why not.
echo "- Configuring Wordpress."
PAGE_ID_HOME=`wp post create --post_type=page --post_title='Home' --post_content='This is a home page.' --post_status='publish' --porcelain`
PAGE_ID_BLOG=`wp post create --post_type=page --post_title='Blog' --post_content='This is a blog index page.' --post_status='publish' --porcelain`

# Update some default options
wp option update show_on_front 'page'
wp option update page_on_front ${PAGE_ID_HOME}
wp option update page_for_posts ${PAGE_ID_BLOG}
wp option update blogdescription "${PROJECT_DESCRIPTION}"
# wp rewrite structure '/%postname%' --hard

# Finished! Display a message.
echo "\n"
echo "${PINK}================================================================="
echo "Installation Complete!"
echo ""
echo "TODO:"
echo "1) Update the salts in the .env file."
echo "2) Update the permalink settings in settings -> permalinks"
echo ""
echo "URLS:"
echo "Site: http://${PROJECT_NAME}.dev"
echo "Admin: http://${PROJECT_NAME}.dev/wp/wp-admin"
echo ""
echo "================================================================="

/usr/bin/open -a "/Applications/Google Chrome.app" "http://${PROJECT_NAME}.dev"

fi
